name: Build Windows Executable

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install mingw-w64
      uses: msys2/setup-msys2@v2
      with:
        msystem: MINGW64
        update: true
        install: mingw-w64-x86_64-gcc

    - name: Build the executable
      shell: bash
      run: 
        x86_64-w64-mingw32-gcc main.c -o your_executable.exe


    - name: Archive artifacts
      uses: actions/upload-artifact@v3  # 将构建好的包上传为GitHub Action的工件
      with:
        name: windows_application_package
        path: dist/  # 假设pyinstaller构建的可执行文件在dist目录下，根据实际情况修改路径
